### ISSUE TITLE
Обращение к записи при пустом слое

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#44]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.forestinspector/com.nextgis.forestinspector.activity.DocumentViewActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394)
	at android.app.ActivityThread.access$800(ActivityThread.java:139)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1293)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5234)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:74)
	at com.nextgis.maplib.datasource.Feature.fromCursor(Feature.java:358)
	at com.nextgis.forestinspector.map.DocumentsLayer.getFeature(DocumentsLayer.java:86)
	at com.nextgis.forestinspector.activity.DocumentViewActivity.onCreate(DocumentViewActivity.java:83)
	at android.app.Activity.performCreate(Activity.java:5411)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
	... 11 more
```

**Comment by NikitaFeodonit** [comment]
Исправлено.
