### ISSUE TITLE
Ошибка при вводе пней (ведомость перечета)

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#57]
```
java.lang.NullPointerException
	at com.nextgis.forestinspector.dialog.SheetListFillerDialog.setFeatureFieldsValues(SheetListFillerDialog.java:160)
	at com.nextgis.forestinspector.dialog.ListFillerDialog.saveData(ListFillerDialog.java:461)
	at com.nextgis.forestinspector.dialog.ListFillerDialog.addData(ListFillerDialog.java:400)
	at com.nextgis.forestinspector.dialog.ListFillerDialog$1.onPositiveClicked(ListFillerDialog.java:223)
	at com.nextgis.maplibui.dialog.StyledDialogFragment$1.onClick(StyledDialogFragment.java:238)
	at android.view.View.performClick(View.java:4487)
	at android.view.View$PerformClick.run(View.java:18746)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:149)
	at android.app.ActivityThread.main(ActivityThread.java:5234)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by NikitaFeodonit** [comment]
Раньше у меня также воспроизводилось. Теперь нет. Возможно, из-за закрытия #62. Закрываю.
