### ISSUE TITLE
Ошибка при первоначальной загрузке

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#82]
```
java.lang.RuntimeException: Error receiving broadcast Intent { act=forestviolate.inspector.sync_message flg=0x10 (has extras) } in com.nextgis.forestinspector.MainApplication$1@41607e30
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:737)
	at android.os.Handler.handleCallback(Handler.java:605)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: account must not be null
	at android.content.ContentResolver.removePeriodicSync(ContentResolver.java:1285)
	at com.nextgis.forestinspector.MainApplication$1.onReceive(MainApplication.java:121)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:728)
	... 9 more
```

**Comment by NikitaFeodonit** [comment]
А какая версия андроида была?
