### ISSUE TITLE
Падение при первоначальной настройке

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#86]
Не очень приоритетная задача.

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@8e7eba2 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:576)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1066)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:970)
	at android.support.v7.internal.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:78)
	at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
	at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:92)
	at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:171)
	at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:682)
	at android.support.v7.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:163)
	at android.support.v7.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:129)
	at android.support.v7.widget.ActionMenuPresenter.onSubMenuSelected(ActionMenuPresenter.java:300)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchSubMenuSelected(MenuBuilder.java:306)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:976)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4764)
	at android.view.View$PerformClick.run(View.java:19844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

Возможно связано с ANR
```
"main" tid=1
	libcore.io.Posix.writeBytes(Native Method)
	libcore.io.Posix.write(Posix.java:223)
	libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
	libcore.io.IoBridge.write(IoBridge.java:497)
	java.io.FileOutputStream.write(FileOutputStream.java:186)
	java.io.DataOutputStream.writeLong(DataOutputStream.java:186)
	java.io.DataOutputStream.writeDouble(DataOutputStream.java:171)
	com.nextgis.maplib.datasource.GeometryRTree$Node.write(GeometryRTree.java:804)
	com.nextgis.maplib.datasource.GeometryRTree$Entry.write(GeometryRTree.java:886)
	com.nextgis.maplib.datasource.GeometryRTree$Node.write(GeometryRTree.java:810)
	com.nextgis.maplib.datasource.GeometryRTree$Node.write(GeometryRTree.java:810)
	com.nextgis.maplib.datasource.GeometryRTree$Node.write(GeometryRTree.java:810)
	com.nextgis.maplib.datasource.GeometryRTree.save(GeometryRTree.java:177)
	com.nextgis.maplib.map.VectorLayer.toJSON(VectorLayer.java:765)
	com.nextgis.maplib.map.NGWVectorLayer.toJSON(NGWVectorLayer.java:206)
	com.nextgis.forestinspector.map.DocumentsLayer.toJSON(DocumentsLayer.java:251)
	com.nextgis.maplib.map.Table.save(Table.java:127)
	com.nextgis.forestinspector.map.DocumentsLayer.save(DocumentsLayer.java:325)
	com.nextgis.maplib.map.VectorLayer.notifyUpdate(VectorLayer.java:2301)
	com.nextgis.maplib.map.MapContentProviderHelper$VectorLayerNotifyReceiver.onReceive(MapContentProviderHelper.java:233)
	android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:956)
	android.os.Handler.handleCallback(Handler.java:739)
	android.os.Handler.dispatchMessage(Handler.java:95)
	android.os.Looper.loop(Looper.java:135)
	android.app.ActivityThread.main(ActivityThread.java:5296)
	java.lang.reflect.Method.invoke(Native Method)
	java.lang.reflect.Method.invoke(Method.java:372)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by NikitaFeodonit** [comment]
А какие действия выполнялись? В каком порядке?

**Comment by BishopGIS** [comment]
История умалчивает. Вот только стэктрейс и остался.

**Comment by NikitaFeodonit** [comment]
Проблема возникла при множестве сообщений об обновлении базы слоев, когда подвисал интерфейс. Сейчас причина устранена. Закрываю.
