### ISSUE TITLE
Падение

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#90]
```
java.lang.RuntimeException: Unable to resume activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1102, result=0, data=null} to activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3019)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3050)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1102, result=0, data=null} to activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3607)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3005)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at com.nextgis.forestinspector.activity.DocumentCreatorActivity.onActivityResult(DocumentCreatorActivity.java:410)
	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
	... 12 more
```

**Comment by BishopGIS** [comment]
И еще
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at com.nextgis.forestinspector.adapter.PhotoTableAdapter$2.onClick(PhotoTableAdapter.java:264)
	at android.view.View.performClick(View.java:4640)
	at android.view.View$PerformClick.run(View.java:19421)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@8e7eba2 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:576)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:272)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1066)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:970)
	at android.support.v7.internal.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:78)
	at android.support.v4.widget.PopupWindowCompatKitKat.showAsDropDown(PopupWindowCompatKitKat.java:30)
	at android.support.v4.widget.PopupWindowCompat$KitKatPopupWindowImpl.showAsDropDown(PopupWindowCompat.java:92)
	at android.support.v4.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:171)
	at android.support.v7.widget.ListPopupWindow.show(ListPopupWindow.java:682)
	at android.support.v7.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:163)
	at android.support.v7.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:129)
	at android.support.v7.widget.ActionMenuPresenter.onSubMenuSelected(ActionMenuPresenter.java:300)
	at android.support.v7.internal.view.menu.MenuBuilder.dispatchSubMenuSelected(MenuBuilder.java:306)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:976)
	at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:619)
	at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
	at android.view.View.performClick(View.java:4764)
	at android.view.View$PerformClick.run(View.java:19844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SyncLoginActivity}: java.lang.IllegalStateException: Fragment already added: LoginFragment{3c9f5bcf #0 id=0x7f0e00b2 SyncLogin}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3951)
	at android.app.ActivityThread.access$900(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1290)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5296)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
Caused by: java.lang.IllegalStateException: Fragment already added: LoginFragment{3c9f5bcf #0 id=0x7f0e00b2 SyncLogin}
	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1330)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:671)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:6036)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2268)
	... 11 more
```

```
java.lang.RuntimeException: Unable to resume activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1102, result=0, data=null} to activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3019)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3050)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
	at android.app.ActivityThread.access$900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5294)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1102, result=0, data=null} to activity {com.nextgis.forestinspector/com.nextgis.forestinspector.activity.SheetCreatorActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3607)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3005)
	... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.nextgis.forestinspector.datasource.DocumentEditFeature.getFieldValueAsString(java.lang.String)' on a null object reference
	at com.nextgis.forestinspector.activity.DocumentCreatorActivity.onActivityResult(DocumentCreatorActivity.java:410)
	at android.app.Activity.dispatchActivityResult(Activity.java:6192)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3603)
	... 12 more
```
