### ISSUE TITLE
Падение при вводе регистрационной информации

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#91]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nextgis.forestinspector/com.nextgis.forestinspector.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.SwitchCompat.isChecked()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5258)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.v7.widget.SwitchCompat.isChecked()' on a null object reference
	at com.nextgis.maplibui.fragment.NGWLoginFragment$LocalTextWatcher.afterTextChanged(NGWLoginFragment.java:354)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:7695)
	at android.widget.TextView.setText(TextView.java:4066)
	at android.widget.TextView.setText(TextView.java:3915)
	at android.widget.EditText.setText(EditText.java:85)
	at android.widget.TextView.setText(TextView.java:3890)
	at com.nextgis.forestinspector.fragment.LoginFragment.onCreateView(LoginFragment.java:68)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1965)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1259)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1624)
	at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
	at android.app.Activity.performStart(Activity.java:6006)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2288)
	... 10 more
```

**Comment by NikitaFeodonit** [comment]
Исправлено.
