### ISSUE TITLE
Падение при заполнении фототаблицы

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#95]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at com.nextgis.forestinspector.adapter.PhotoTableAdapter$2.onClick(PhotoTableAdapter.java:264)
	at android.view.View.performClick(View.java:4640)
	at android.view.View$PerformClick.run(View.java:19421)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

Падение происходит при вводе описания к фото

**Comment by NikitaFeodonit** [comment]
Какая система была, pre-Honeycomb или post-Honeycomb ?

**Comment by NikitaFeodonit** [comment]
У меня не повторяется. Сейчас сделал исправление, но тикет не закрываю, проверь, пожалуйста.

**Comment by BishopGIS** [comment]
Это наш планшет Galaxy Note 8. На телефоне не падает, а на планшете - падает. ОС 4.4.2

**Comment by NikitaFeodonit** [comment]
Проверь с новым исправлением, пожалуйста.

**Comment by BishopGIS** [comment]
Все равно падает
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:613)
	at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
	at com.nextgis.forestinspector.adapter.PhotoTableAdapter$2.onClick(PhotoTableAdapter.java:264)
	at android.view.View.performClick(View.java:4640)
	at android.view.View$PerformClick.run(View.java:19421)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
```

Что заметил. После того как фото сделано во встроенном приложении, оно меняет ориентацию экрана. В результате после принятия фотки, в сетке - она открывается в альбомной ориентации и потом сразу переходит в вертикальную. После этого, при щелчке на фото для добавления  подписи - падение. 
На телефоне такого не было, т.к. поворота не было.
