### ISSUE TITLE
Падение при вводе геометрии обходом

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/mobile.forestviolate.inspector#98]
```
java.lang.RuntimeException: Unable to start service com.nextgis.maplibui.service.WalkEditService@423ab790 with Intent { act=com.nextgis.maplibui.WALKEDIT_START cmp=com.nextgis.forestinspector/com.nextgis.maplibui.service.WalkEditService (has extras) }: java.lang.ClassCastException: java.lang.Integer cannot be cast to com.nextgis.maplib.datasource.GeoGeometry
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2906)
	at android.app.ActivityThread.access$2200(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5487)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to com.nextgis.maplib.datasource.GeoGeometry
	at com.nextgis.maplibui.service.WalkEditService.onStartCommand(WalkEditService.java:114)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2889)
	... 10 more
```

**Comment by NikitaFeodonit** [comment]
Падение возникает в maplibui тут:
https://github.com/nextgis/android_maplibui/blob/master/src/main/java/com/nextgis/maplibui/service/WalkEditService.java#L114
из-за того, что в самом приложении передается не GeoGeometry, а int тут:
https://github.com/nextgis/mobile.forestviolate.inspector/blob/master/app/src/main/java/com/nextgis/forestinspector/overlay/EditTerritoryOverlay.java#L889
